# Generated by Django 4.0.2 on 2022-07-18 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
