# Generated by Django 4.0.2 on 2022-07-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_component_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['-due_date']},
        ),
    ]
